handle add promotion
AT-PHPIntership/winter-2018-computer-shop pull request #60
Opened 2019-02-14 07:46 UTC by at-thanhnguyen2

2019-02-14 09:39 UTC, at-quangtran commented on app/Services/PromotionService.php
> +            $arrayProuctId = [];
sai chính tả $arrayProuctId

2019-02-14 09:42 UTC, at-quangtran commented on app/Services/PromotionService.php
> +        $products = Product::where('total_sold', '<', $totalSold)->get();
thay đoạn   
$products = Product::where('total_sold', '<', $totalSold)->get();
foreach ($products as $value) {
            array_push($arrayProuctId, $value->id);
}
bằng $productIds= Product::where('total_sold', '<', $totalSold)->pluck('id');
thay  đoạn : 
Promotion::find($promotion->id)->products()->sync($arrayProuctId);
bằng 
$promotion->->products()->sync($productIds);

2019-02-14 09:44 UTC, at-quangtran commented on app/Services/PromotionService.php
> +            $arrayProuctId = [];
sửa lại như comment của hàm create

2019-02-14 09:47 UTC, at-quangtran commented on resources/lang/en/master.php
> +            'total_sold' => 'Total Sold Product',
cái total sold này thực ra là điều kiện để lọc product nào đc dùng promotion này đúng ko? 
Nếu rứa thì khi hiển thị list promotion thì cột total_sold này phải ghi là điều kiện khuyến mãi (sold quantity > ..)

2019-02-14 09:48 UTC, mvn-quangtran-dn requested changes
check comment

2019-02-15 08:02 UTC, mvn-quangtran-dn approved these changes
LGTM

2019-02-15 08:02 UTC, merged